-- Run as ITROHA on XEPDB1
CREATE TABLE upload_notifications (
    id           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message      VARCHAR2(4000),
    folder       VARCHAR2(100),
    file_count   NUMBER(10)      NOT NULL,
    total_size   NUMBER(18)      NOT NULL,
    files_detail CLOB,
    sent_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sent_by      VARCHAR2(256),
    ip_address   VARCHAR2(50)
);
