-- Run as ITROHA on XEPDB1
CREATE TABLE upload_logs (
    id            NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name     VARCHAR2(500)  NOT NULL,
    original_name VARCHAR2(500)  NOT NULL,
    content_type  VARCHAR2(200),
    file_size     NUMBER(18)     NOT NULL,
    uploaded_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_address    VARCHAR2(50)
);
