-- Run as ITROHA on XEPDB1 (localhost:1521/XEPDB1)
CREATE TABLE download_logs (
    id              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_log_id   NUMBER          NOT NULL,
    downloaded_at   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_address      VARCHAR2(50),
    CONSTRAINT fk_download_upload FOREIGN KEY (upload_log_id)
        REFERENCES upload_logs (id) ON DELETE CASCADE
);

CREATE INDEX ix_download_logs_upload_id ON download_logs (upload_log_id);
